apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-quarkus-wlhewnlt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-quarkus-wlhewnlt:d1a2a85247fd4481b8b78136fa9a9b515ff32078@sha256:e338a1879476bafd76f6c9b999e6d79f7645af8598da67634456ee18ab7eaaa9
          name: container-image
